// Shopping cart
export const SC_REMOVE_FROM_CART = 'SC_REMOVE_FROM_CART';
export const SC_ADD_TO_CART = 'SC_ADD_TO_CART';
export const SC_MODIFY_CART_ITEM = 'SC_MODIFY_CART_ITEM';
export const SC_CLEAR_CART = 'SC_CLEAR_CART';
export const SC_SHOW_POPUP = 'SC_SHOW_POPUP';
export const SC_CONFIRM_REMOVE_ITEM = 'SC_CONFIRM_REMOVE_ITEM';
export const SC_CANCEL_REMOVE_ITEM = 'SC_CANCEL_REMOVE_ITEM';

// Product details
export const PD_ADD_TO_CART_SUCCESSFUL = 'PD_ADD_TO_CART_SUCCESSFUL';
export const PD_ADD_TO_CART_SUCCESSFUL_CONFIRMED = 'PD_ADD_TO_CART_SUCCESSFUL_CONFIRMED';

// Checkout
export const CO_SUBMIT = 'CO_SUBMIT';

// ui